/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package work;

import java.util.Arrays;
import java.util.LinkedList;

public class Library {

    public boolean someLibraryMethod() {
        return true;
    }
}
