/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.Arrays;
import java.util.LinkedList;

class Restaurant{
    protected Review review;
    private int counter=1;
    protected String name;
    protected int stars;
    protected String price;
    public Restaurant(String name,int stars,int price){
        this.name=name;
        setStars(stars);
        setPrice(price);
    }
    public String toString(){
        return "the Restaurant's name: " +this.name+ "\n\rNumber of stars: "+this.stars+"\n\rPrices: " +this.price;
    }
    public void setStars(int stars){      if (stars >= 0 && stars <= 5) {
        this.stars = stars;
        return;
    } else if (stars>5) {
        this.stars=5;
        return;
    }
        this.stars=0;
        return;
    }
    public void setPrice(int number){
     String price="";
        for (int i = 0; i < number; i++) {
            price+="$";
        }
        this.price=price;
    }
    public void addReview(String body ,String author ,int stars , Restaurant reviewedRestaurant ){
        Review newReview= new Review(body,author,stars);
        this.review=newReview;
        calculateStarsAfterReview(stars);
    }
    public void calculateStarsAfterReview(int newReviewStars) {
        this.stars = (counter * this.stars + newReviewStars) / (counter + 1);
        counter++;
    }


}
class Review{
    protected String body;
    protected String author;
    protected int stars;
     public Review(String body,String author, int stars ){
        this.body=body;
        this.author=author;
        setStars(stars);
    }
    public void setStars (int stars){
         if (stars >= 0 && stars <= 5) {
        this.stars = stars;
        return;
    } else if (stars>5) {
        this.stars=5;
        return;
    }
        this.stars=0;
        return;
    }
    public String toString (){
       return "Review by "+this.author+"\r\nStars: "+this.stars+"\r\nReview: "+this.body;
    }



}
public class Library {

    public boolean someLibraryMethod() {
        return true;
    }
}
