/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RestaurantTest {

    @Test
    void testRestaurantConstructor() {
        Restaurant restaurant = new Restaurant("Sample Restaurant", 4, 2);
        assertEquals("Sample Restaurant", restaurant.name);
        assertEquals(4, restaurant.stars);
        assertEquals("$$", restaurant.price); // Check if price is correct based on 2 dollar signs
    }
    @Test
    void testReviewConstructor() {
        Review review = new Review("Great food!", "John Doe", 5);

        assertEquals("Great food!", review.body);
        assertEquals("John Doe", review.author);
        assertEquals(5, review.stars);
    }

    @Test
    void testStarRatingUpdate() {
        Restaurant restaurant = new Restaurant("Sample Restaurant", 4, 2);
        Review review = new Review("Great food!", "John Doe", 5);
        restaurant.addReview(review.body, review.author, review.stars, restaurant);
        assertEquals(4, restaurant.stars); // Initial rating was 4, and the new review is 5 stars
    }
    @Test
    void testRestaurantToString() {
        Restaurant restaurant = new Restaurant("Sample Restaurant", 4, 2);

        String expected = "the Restaurant's name: Sample Restaurant\n\rNumber of stars: 4\n\rPrices: $$";
        assertEquals(expected, restaurant.toString());
    }

    @Test
    void testReviewToString() {
        // Create an instance of the Review class
        Review review = new Review("Great food!", "John Doe", 5);

        // Define the expected string representation with dynamic line separators
        String expected = "Review by John Doe" + System.lineSeparator()
                + "Stars: 5" + System.lineSeparator()
                + "Review: Great food!";

        // Verify the string representation using assertEquals with dynamic line separators
        assertEquals(expected, review.toString());
    }
}
